import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/ui/componentes/Header";
import Footer from "@/ui/componentes/Footer";
import { GlobalProvider } from "@/ui/context/GlobalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Domba App",
  description: "Generated by UNIVESP students",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GlobalProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          {children}
          {/* <Footer /> */}
        </body>
      </html>
    </GlobalProvider>
  );
}
