import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/ui/componentes/Header';
import Footer from '@/ui/componentes/Footer';
import { GlobalProvider } from '@/ui/context/GlobalContext';
import { GoogleTagManager } from '@next/third-parties/google';

const inter = Inter({ subsets: ['latin'] });
const gtmTag = process.env.GTM_TAG || '';

export const metadata: Metadata = {
  title: 'Domba App',
  description: 'Generated by UNIVESP students',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GlobalProvider>
      <html lang="en">
        <GoogleTagManager gtmId={gtmTag} />
        <body className={inter.className}>
          <Header />
          {children}
          {/* <Footer /> */}
        </body>
      </html>
    </GlobalProvider>
  );
}
